
package Interface;

import SystemManagement.ServiceDB;

import java.io.FileWriter;
import java.io.IOException;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;


public class Transfer extends javax.swing.JInternalFrame {
    private static FileWriter csvWriter;
    private static ServiceDB serviceDB;

    public Transfer(FileWriter csvWriterMain, ServiceDB serviceDBMain) {
        csvWriter = csvWriterMain;
        serviceDB = serviceDBMain;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        sendFromPanel = new javax.swing.JPanel();
        amountToSendLabel = new javax.swing.JLabel();
        sendFromIBANTextField = new javax.swing.JTextField();
        sendFromCurrBalanceLabel = new javax.swing.JLabel();
        sendFromCurrBalanceEticheta = new javax.swing.JLabel();
        sendFromIBANLabel = new javax.swing.JLabel();
        amountToSendTextField = new javax.swing.JTextField();
        findIBANFromButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        sendFromIDLabel = new javax.swing.JLabel();
        sendButton = new javax.swing.JButton();
        switchButton = new javax.swing.JButton();
        sendToPanel = new javax.swing.JPanel();
        sendToIBANTextField = new javax.swing.JTextField();
        sendToCurrBalanceLabel = new javax.swing.JLabel();
        sendToCurrBalanceEticheta = new javax.swing.JLabel();
        sendToIBANLabel = new javax.swing.JLabel();
        findIBANToButton = new javax.swing.JButton();
        sendToIDLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();

        sendFromPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Send from", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 1, 18))); // NOI18N

        amountToSendLabel.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        amountToSendLabel.setText("Amount to send");

        sendFromIBANTextField.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        sendFromIBANTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendFromIBANTextFieldActionPerformed(evt);
            }
        });

        sendFromCurrBalanceLabel.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        sendFromCurrBalanceLabel.setPreferredSize(new java.awt.Dimension(108, 25));

        sendFromCurrBalanceEticheta.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        sendFromCurrBalanceEticheta.setText("Current Balance");

        sendFromIBANLabel.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        sendFromIBANLabel.setText("Enter IBAN");

        amountToSendTextField.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        amountToSendTextField.setPreferredSize(new java.awt.Dimension(108, 20));
        amountToSendTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amountToSendTextFieldActionPerformed(evt);
            }
        });

        findIBANFromButton.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        findIBANFromButton.setText("Find");
        findIBANFromButton.setPreferredSize(new java.awt.Dimension(50, 25));
        findIBANFromButton.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                findIBANFromButtonStateChanged(evt);
            }
        });
        findIBANFromButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    findIBANFromButtonActionPerformed(evt);
                } catch (SQLException throwables) {
                    throwables.printStackTrace();
                }
            }
        });

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel1.setText("Account");

        sendFromIDLabel.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        sendFromIDLabel.setForeground(new java.awt.Color(102, 0, 102));
        sendFromIDLabel.setPreferredSize(new java.awt.Dimension(60, 19));

        sendButton.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        sendButton.setText("SEND");
        sendButton.setPreferredSize(new java.awt.Dimension(80, 32));
        sendButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    sendButtonActionPerformed(evt);
                } catch (SQLException | IOException throwables) {
                    throwables.printStackTrace();
                }
            }
        });

        javax.swing.GroupLayout sendFromPanelLayout = new javax.swing.GroupLayout(sendFromPanel);
        sendFromPanel.setLayout(sendFromPanelLayout);
        sendFromPanelLayout.setHorizontalGroup(
                sendFromPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(sendFromPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(sendFromPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(sendFromPanelLayout.createSequentialGroup()
                                                .addComponent(jLabel1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(sendFromIDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                        .addGroup(sendFromPanelLayout.createSequentialGroup()
                                                .addGroup(sendFromPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(sendFromPanelLayout.createSequentialGroup()
                                                                .addGroup(sendFromPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(amountToSendLabel)
                                                                        .addComponent(sendFromCurrBalanceEticheta)
                                                                        .addComponent(sendFromCurrBalanceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(sendFromIBANLabel))
                                                                .addGap(0, 0, Short.MAX_VALUE))
                                                        .addGroup(sendFromPanelLayout.createSequentialGroup()
                                                                .addGroup(sendFromPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                                        .addGroup(sendFromPanelLayout.createSequentialGroup()
                                                                                .addComponent(amountToSendTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                                .addComponent(sendButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                        .addComponent(sendFromIBANTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                                                                .addComponent(findIBANFromButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addContainerGap())))
        );
        sendFromPanelLayout.setVerticalGroup(
                sendFromPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(sendFromPanelLayout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(sendFromPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel1)
                                        .addComponent(sendFromIDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(27, 27, 27)
                                .addComponent(sendFromIBANLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(sendFromPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(sendFromIBANTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(findIBANFromButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(37, 37, 37)
                                .addComponent(sendFromCurrBalanceEticheta)
                                .addGap(12, 12, 12)
                                .addComponent(sendFromCurrBalanceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(amountToSendLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(sendFromPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(amountToSendTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(sendButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        switchButton.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        switchButton.setText("SWITCH");
        switchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                switchButtonActionPerformed(evt);
            }
        });

        sendToPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Send to", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 1, 18))); // NOI18N

        sendToIBANTextField.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        sendToIBANTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendToIBANTextFieldActionPerformed(evt);
            }
        });

        sendToCurrBalanceLabel.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        sendToCurrBalanceLabel.setPreferredSize(new java.awt.Dimension(108, 25));

        sendToCurrBalanceEticheta.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        sendToCurrBalanceEticheta.setText("Current Balance");

        sendToIBANLabel.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        sendToIBANLabel.setText("Enter IBAN");

        findIBANToButton.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        findIBANToButton.setText("Find");
        findIBANToButton.setPreferredSize(new java.awt.Dimension(50, 25));
        findIBANToButton.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                findIBANToButtonStateChanged(evt);
            }
        });
        findIBANToButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    findIBANToButtonActionPerformed(evt);
                } catch (SQLException throwables) {
                    throwables.printStackTrace();
                }
            }
        });

        sendToIDLabel.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        sendToIDLabel.setForeground(new java.awt.Color(102, 0, 102));
        sendToIDLabel.setPreferredSize(new java.awt.Dimension(60, 19));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel3.setText("Account");

        javax.swing.GroupLayout sendToPanelLayout = new javax.swing.GroupLayout(sendToPanel);
        sendToPanel.setLayout(sendToPanelLayout);
        sendToPanelLayout.setHorizontalGroup(
                sendToPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(sendToPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(sendToPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(sendToPanelLayout.createSequentialGroup()
                                                .addGroup(sendToPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(sendToCurrBalanceEticheta)
                                                        .addComponent(sendToCurrBalanceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(sendToIBANLabel))
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(sendToPanelLayout.createSequentialGroup()
                                                .addComponent(sendToIBANTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(findIBANToButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(sendToPanelLayout.createSequentialGroup()
                                                .addComponent(jLabel3)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(sendToIDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE))))
        );
        sendToPanelLayout.setVerticalGroup(
                sendToPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(sendToPanelLayout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(sendToPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel3)
                                        .addComponent(sendToIDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(27, 27, 27)
                                .addComponent(sendToIBANLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(sendToPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(sendToIBANTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(findIBANToButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(39, 39, 39)
                                .addComponent(sendToCurrBalanceEticheta)
                                .addGap(12, 12, 12)
                                .addComponent(sendToCurrBalanceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        backButton.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        backButton.setText("BACK");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(sendFromPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(sendToPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10))
                        .addGroup(layout.createSequentialGroup()
                                .addGap(313, 313, 313)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(switchButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(backButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(sendFromPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(sendToPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(switchButton)
                                .addGap(18, 18, 18)
                                .addComponent(backButton)
                                .addContainerGap(2317, Short.MAX_VALUE))
        );

        pack();
    }

    private void switchButtonActionPerformed(java.awt.event.ActionEvent evt) {
        String moveID = sendFromIDLabel.getText();
        sendFromIDLabel.setText(sendToIDLabel.getText());
        sendToIDLabel.setText(moveID);

        String moveIBAN = sendFromIBANTextField.getText();
        sendFromIBANTextField.setText(sendToIBANTextField.getText());
        sendToIBANTextField.setText(moveIBAN);

        String moveBalance = sendFromCurrBalanceLabel.getText();
        sendFromCurrBalanceLabel.setText(sendToCurrBalanceLabel.getText());
        sendToCurrBalanceLabel.setText(moveBalance);
    }

    private void sendFromIBANTextFieldActionPerformed(java.awt.event.ActionEvent evt) {
    }

    private void sendToIBANTextFieldActionPerformed(java.awt.event.ActionEvent evt) {
    }

    private void amountToSendTextFieldActionPerformed(java.awt.event.ActionEvent evt) {
    }

    private void findIBANFromButtonStateChanged(javax.swing.event.ChangeEvent evt) {
    }

    private void findIBANFromButtonActionPerformed(java.awt.event.ActionEvent evt) throws SQLException {
        String iban = sendFromIBANTextField.getText();
        ResultSet id_account = serviceDB.findAccountByIBAN(iban);
        if(id_account.next()) {
            sendFromIDLabel.setText(id_account.getString(1));
            ResultSet currentBalance = serviceDB.getCurrentBalance(id_account.getString(1));
            if(currentBalance.next()) {
                sendFromCurrBalanceLabel.setText(currentBalance.getString(1));
            } else {
                JOptionPane.showMessageDialog(this, "Nu se poate obtine soldul curent");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Nu exista niciun cont cu acest IBAN");
        }
    }

    private void findIBANToButtonStateChanged(javax.swing.event.ChangeEvent evt) {
        // TODO add your handling code here:
    }

    private void findIBANToButtonActionPerformed(java.awt.event.ActionEvent evt) throws SQLException {
        // TODO add your handling code here:
        String iban = sendToIBANTextField.getText();
        ResultSet id_account = serviceDB.findAccountByIBAN(iban);
        if(id_account.next()) {
            sendToIDLabel.setText(id_account.getString(1));
            ResultSet currentBalance = serviceDB.getCurrentBalance(id_account.getString(1));
            if(currentBalance.next()) {
                sendToCurrBalanceLabel.setText(currentBalance.getString(1));
            } else {
                JOptionPane.showMessageDialog(this, "Nu se poate obtine soldul curent");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Nu exista niciun cont cu acest IBAN");
        }
    }

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {
        backButton.setVisible(false);
        this.dispose();
    }

    private void sendButtonActionPerformed(java.awt.event.ActionEvent evt) throws SQLException, IOException {
        Float amount = Float.parseFloat(amountToSendTextField.getText() + "f");
        Float currentBalance = Float.parseFloat(sendFromCurrBalanceLabel.getText() + "f");

        if(amount > currentBalance) {
            JOptionPane.showMessageDialog(this, "Nu puteti trimite o suma mai mare decat cea existenta in cont");
        } else {
            String id_sender = sendFromIDLabel.getText();
            String id_receiver = sendToIDLabel.getText();

            boolean statusSend = serviceDB.updateBalance(id_sender, -amount);
            boolean statusReceive = serviceDB.updateBalance(id_receiver, amount);

            if (statusReceive && statusSend) {
                JOptionPane.showMessageDialog(this, "Transfer efectuat cu succes");
                ResultSet balance_sender = serviceDB.getCurrentBalance(id_sender);
                ResultSet balance_receiver = serviceDB.getCurrentBalance(id_receiver);
                if(balance_sender.next() && balance_receiver.next()) {
                    sendFromCurrBalanceLabel.setText(balance_sender.getString(1));
                    sendToCurrBalanceLabel.setText(balance_receiver.getString(1));
                    serviceDB.writeInAuditLog(csvWriter,"Transfer bancar", String.valueOf(Thread.currentThread().getId()), Thread.currentThread().getName());
                } else {
                    JOptionPane.showMessageDialog(this, "Nu se pot obtine soldurile curente actualizate");
                }

            }
        }
    }


    // Variables declaration - do not modify
    private javax.swing.JLabel amountToSendLabel;
    private javax.swing.JTextField amountToSendTextField;
    private javax.swing.JButton backButton;
    private javax.swing.JButton findIBANFromButton;
    private javax.swing.JButton findIBANToButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton sendButton;
    private javax.swing.JLabel sendFromCurrBalanceEticheta;
    private javax.swing.JLabel sendFromCurrBalanceLabel;
    private javax.swing.JLabel sendFromIBANLabel;
    private javax.swing.JTextField sendFromIBANTextField;
    private javax.swing.JLabel sendFromIDLabel;
    private javax.swing.JPanel sendFromPanel;
    private javax.swing.JLabel sendToCurrBalanceEticheta;
    private javax.swing.JLabel sendToCurrBalanceLabel;
    private javax.swing.JLabel sendToIBANLabel;
    private javax.swing.JTextField sendToIBANTextField;
    private javax.swing.JLabel sendToIDLabel;
    private javax.swing.JPanel sendToPanel;
    private javax.swing.JButton switchButton;
    // End of variables declaration
}
